export const productData = [
    {
        id: 1,
        imageUrl: "/NewArrival/img1.png",
        name: "T-SHIRT WITH TAPE DETAILS",
        price: 120,
        rating: 4.5,
        tag: ["New Arrival", "Men"],
    },
    {
        id: 2,
        discount: 20,
        imageUrl: "/NewArrival/img2.png",
        name: "SKINNY FIT JEANS",
        price: 240,
        originalPrice: 260,
        rating: 3.5,
        tag: ["New Arrival", "Men"],
    },
    {
        id: 3,
        imageUrl: "/NewArrival/img3.png",
        name: "CHECKERED SHIRT",
        price: 180,
        rating: 4.5,
        tag: ["New Arrival", "Men"],
    },
    {
        id: 4,
        discount: 30,
        imageUrl: "/NewArrival/img4.png",
        name: "SLEEVE STRIPED T-SHIRT",
        price: 130,
        originalPrice: 160,
        rating: 4.5,
        tag: ["New Arrival", "Men"],
    },
    {
        id:1,
        discount: 20,
        imageUrl: "/TopSelling/img1.png",
        name: "VERTICAL STRIPED SHIRT",
        price: 212,
        originalPrice: 232,
        rating: 5.0,
        tag: ["Top Selling", "Men"],
      },
      {
          id:2,
        imageUrl: "/TopSelling/img2.png",
        name: "COURAGE GRAPHIC T-SHIRT",
        price: 145,
        rating: 4.0,
        tag: ["Top Selling", "Men"],
      },
      {
        id:3,
        imageUrl: "/TopSelling/img3.png",
        name: "LOOSE FIT BERMUDA SHORTS",
        price: 80,
        rating: 3.0,
        tag: ["Top Selling", "Men"],
      },
      {
        id:4,
        imageUrl: "/TopSelling/img4.png",
        name: "FADED SKINNY JEANS",
        price: 210,
        rating: 4.5,
        tag: ["Top Selling", "Men"],
      },
      {
        id: 1,
        imageUrl: "/suggestion/img2.png",
        name: "Gradient Graphic T-shirt",
        price: 145,
        rating: 3.5,
        tag: ["Casual", "Men"],
      },
      {
        id: 2,
        imageUrl: "/suggestion/img3.png",
        name: "Polo with Tipping Details",
        price: 180,
        rating: 4.5,
        tag: ["Casual", "Men"],
      },
      {
        id: 3,
        discount: 30,
        imageUrl: "/suggestion/img4.png",
        name: "Black Striped T-shirt",
        price: 120,
        originalPrice: 150,
        rating: 5.0,
        tag: ["Casual", "Men"],
      },
      {
        id: 4,
        discount: 20,
        imageUrl: "/NewArrival/img2.png",
        name: "SKINNY FIT JEANS",
        price: 240,
        originalPrice: 260,
        rating: 3.5,
        tag: ["Casual", "Men"],
      },
      {
        id: 5,
        imageUrl: "/NewArrival/img3.png",
        name: "CHECKERED SHIRT",
        price: 180,
        rating: 4.5,
        tag: ["Casual", "Men"],
      },
      {
        id: 6,
        discount: 30,
        imageUrl: "/NewArrival/img4.png",
        name: "SLEEVE STRIPED T-SHIRT",
        price: 130,
        originalPrice: 160,
        rating: 4.5,
        tag: ["Casual", "Men"],
      },
      {
        id: 7,
        discount: 20,
        imageUrl: "/TopSelling/img1.png",
        name: "VERTICAL STRIPED SHIRT",
        price: 212,
        originalPrice: 232,
        rating: 5.0,
        tag: ["Casual", "Men"],
      },
      {
        id: 8,
        imageUrl: "/TopSelling/img2.png",
        name: "COURAGE GRAPHIC T-SHIRT",
        price: 145,
        rating: 4.0,
        tag: ["Casual", "Men"],
      },
      {
        id: 9,
        imageUrl: "/TopSelling/img3.png",
        name: "LOOSE FIT BERMUDA SHORTS",
        price: 80,
        rating: 3.0,
        tag: ["Casual", "Men", "Gym"],
      },
    
];